### ISSUE TITLE
какая альтернатива <iostream>

### ISSUE THREAD

**Issue by oleg-tgn** [shalyginaviktoria/OAip_labs_Shalygina#1]
https://github.com/shalyginaviktoria/OAip_labs_Shalygina/blob/53c53e1237746e426c706f12b3c46af96c9a9814/%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%821/%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%821/Source.cpp#L3

<iostream> - библиотека c++
есть ли альтернатива для языка си, чтобы делать задержку на экране и не использовать эту библиотеку?

**Comment by shalyginaviktoria** [comment]
#include <conio.h>
getch();

**Comment by oleg-tgn** [comment]
Отлично. Давайте так и впишем, пусть будет код с содержанием только СИ-библиотек

**Comment by oleg-tgn** [comment]
Я запустил у себя. VS написала ошибку и сказала использовать _getch() вместо него.
Это просто частичная обратная совместимость с СИ.

Давайте так и сделаем
